# Generated by Django 4.0.4 on 2022-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0004_auto_20211130_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='old_room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
